version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: vallegrande_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vallegrande_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    command: --mysql-native-password=ON
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: